# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import vericite_lms_client
from vericite_lms_client.rest import ApiException
from vericite_lms_client.models.webhook import Webhook


class TestWebhook(unittest.TestCase):
    """ Webhook unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhook(self):
        """
        Test Webhook
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = vericite_lms_client.models.webhook.Webhook()
        pass


if __name__ == '__main__':
    unittest.main()
