# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import vericite_lms_client
from vericite_lms_client.rest import ApiException
from vericite_lms_client.apis.reports_api import ReportsApi


class TestReportsApi(unittest.TestCase):
    """ ReportsApi unit test stubs """

    def setUp(self):
        self.api = vericite_lms_client.apis.reports_api.ReportsApi()

    def tearDown(self):
        pass

    def test_get_report_urls(self):
        """
        Test case for get_report_urls

        
        """
        pass

    def test_get_scores(self):
        """
        Test case for get_scores

        
        """
        pass

    def test_submit_request(self):
        """
        Test case for submit_request

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
