# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import vericite_lms_client
from vericite_lms_client.rest import ApiException
from vericite_lms_client.models.external_content_upload_info import ExternalContentUploadInfo


class TestExternalContentUploadInfo(unittest.TestCase):
    """ ExternalContentUploadInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalContentUploadInfo(self):
        """
        Test ExternalContentUploadInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = vericite_lms_client.models.external_content_upload_info.ExternalContentUploadInfo()
        pass


if __name__ == '__main__':
    unittest.main()
