# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import vericite_lms_client
from vericite_lms_client.rest import ApiException
from vericite_lms_client.apis.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """ WebhooksApi unit test stubs """

    def setUp(self):
        self.api = vericite_lms_client.apis.webhooks_api.WebhooksApi()

    def tearDown(self):
        pass

    def test_create_webhook(self):
        """
        Test case for create_webhook

        
        """
        pass

    def test_delete_webhook(self):
        """
        Test case for delete_webhook

        
        """
        pass

    def test_get_webhooks(self):
        """
        Test case for get_webhooks

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
