# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class WebhooksApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def create_webhook(self, consumer, consumer_secret, webhook, **kwargs):
        """
        Create/update webhook for event
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.create_webhook(consumer, consumer_secret, webhook, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param Webhook webhook: (required)
        :return: Webhook
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.create_webhook_with_http_info(consumer, consumer_secret, webhook, **kwargs)
        else:
            (data) = self.create_webhook_with_http_info(consumer, consumer_secret, webhook, **kwargs)
            return data

    def create_webhook_with_http_info(self, consumer, consumer_secret, webhook, **kwargs):
        """
        Create/update webhook for event
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.create_webhook_with_http_info(consumer, consumer_secret, webhook, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param Webhook webhook: (required)
        :return: Webhook
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['consumer', 'consumer_secret', 'webhook']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_webhook" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'consumer' is set
        if ('consumer' not in params) or (params['consumer'] is None):
            raise ValueError("Missing the required parameter `consumer` when calling `create_webhook`")
        # verify the required parameter 'consumer_secret' is set
        if ('consumer_secret' not in params) or (params['consumer_secret'] is None):
            raise ValueError("Missing the required parameter `consumer_secret` when calling `create_webhook`")
        # verify the required parameter 'webhook' is set
        if ('webhook' not in params) or (params['webhook'] is None):
            raise ValueError("Missing the required parameter `webhook` when calling `create_webhook`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'consumer' in params:
            header_params['consumer'] = params['consumer']
        if 'consumer_secret' in params:
            header_params['consumerSecret'] = params['consumer_secret']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'webhook' in params:
            body_params = params['webhook']
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/webhooks', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Webhook',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def delete_webhook(self, consumer, consumer_secret, webhook, **kwargs):
        """
        Delete webhook for event
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_webhook(consumer, consumer_secret, webhook, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param Webhook webhook: (required)
        :return: Webhook
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.delete_webhook_with_http_info(consumer, consumer_secret, webhook, **kwargs)
        else:
            (data) = self.delete_webhook_with_http_info(consumer, consumer_secret, webhook, **kwargs)
            return data

    def delete_webhook_with_http_info(self, consumer, consumer_secret, webhook, **kwargs):
        """
        Delete webhook for event
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_webhook_with_http_info(consumer, consumer_secret, webhook, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param Webhook webhook: (required)
        :return: Webhook
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['consumer', 'consumer_secret', 'webhook']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_webhook" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'consumer' is set
        if ('consumer' not in params) or (params['consumer'] is None):
            raise ValueError("Missing the required parameter `consumer` when calling `delete_webhook`")
        # verify the required parameter 'consumer_secret' is set
        if ('consumer_secret' not in params) or (params['consumer_secret'] is None):
            raise ValueError("Missing the required parameter `consumer_secret` when calling `delete_webhook`")
        # verify the required parameter 'webhook' is set
        if ('webhook' not in params) or (params['webhook'] is None):
            raise ValueError("Missing the required parameter `webhook` when calling `delete_webhook`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'consumer' in params:
            header_params['consumer'] = params['consumer']
        if 'consumer_secret' in params:
            header_params['consumerSecret'] = params['consumer_secret']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'webhook' in params:
            body_params = params['webhook']
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/webhooks', 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Webhook',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_webhooks(self, consumer, consumer_secret, **kwargs):
        """
        Retrieves webhooks for the consumer
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_webhooks(consumer, consumer_secret, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param str event: optional event filter
        :return: list[Webhook]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_webhooks_with_http_info(consumer, consumer_secret, **kwargs)
        else:
            (data) = self.get_webhooks_with_http_info(consumer, consumer_secret, **kwargs)
            return data

    def get_webhooks_with_http_info(self, consumer, consumer_secret, **kwargs):
        """
        Retrieves webhooks for the consumer
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_webhooks_with_http_info(consumer, consumer_secret, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str consumer: the consumer (required)
        :param str consumer_secret: the consumer secret (required)
        :param str event: optional event filter
        :return: list[Webhook]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['consumer', 'consumer_secret', 'event']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_webhooks" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'consumer' is set
        if ('consumer' not in params) or (params['consumer'] is None):
            raise ValueError("Missing the required parameter `consumer` when calling `get_webhooks`")
        # verify the required parameter 'consumer_secret' is set
        if ('consumer_secret' not in params) or (params['consumer_secret'] is None):
            raise ValueError("Missing the required parameter `consumer_secret` when calling `get_webhooks`")


        collection_formats = {}

        path_params = {}

        query_params = []
        if 'event' in params:
            query_params.append(('event', params['event']))

        header_params = {}
        if 'consumer' in params:
            header_params['consumer'] = params['consumer']
        if 'consumer_secret' in params:
            header_params['consumerSecret'] = params['consumer_secret']

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/webhooks', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='list[Webhook]',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
