# coding: utf-8

"""
    VeriCiteLmsApiV1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.assignment_data import AssignmentData
from .models.error import Error
from .models.external_content_data import ExternalContentData
from .models.external_content_upload_info import ExternalContentUploadInfo
from .models.report_meta_data import ReportMetaData
from .models.report_score_reponse import ReportScoreReponse
from .models.report_url_link_response import ReportURLLinkResponse
from .models.webhook import Webhook

# import apis into sdk package
from .apis.assignments_api import AssignmentsApi
from .apis.reports_api import ReportsApi
from .apis.webhooks_api import WebhooksApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
